name: mobile_desktop
description: Enterprise Cloud Storage Sync Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0
  http: ^1.2.0
  path_provider: ^2.1.0
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.20.0

flutter:
  uses-material-design: true
